[package]
name = "tide-app"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
tide.workspace = true
tide-tracing = "0.0.12"
tracing-tree = "0.2.3"
